import { expect, it } from 'vitest';
import { renderToStaticMarkup } from 'react-dom/server';
import { LineupPanel } from '../src/LineupPanel.js';
import { snapshot } from './fixtures.js';
import { sample } from './lineup-fixtures.js';
import type { DraftSnapshot } from '../src/api.js';
const render=(value:DraftSnapshot,busy=false,notice='')=>renderToStaticMarkup(<LineupPanel snapshot={value} busy={busy} error="" notice={notice} checking={false} generate={()=>{}} confirm={()=>{}} recheck={()=>{}}/>);
it('created offers generate with no fictitious members',()=>{const html=render(snapshot);expect(html).toContain('生成阵容');expect(html).not.toContain('member-card');});
it('generating is honest progress without generation/confirmation actions',()=>{const html=render(sample('generating_lineup'));expect(html).toContain('正在生成主持人与专家阵容……');expect(html).not.toContain('>确认阵容<');expect(html).not.toContain('member-card');});
it('ready shows all identity fields, server color, unconfirmed and exact actions',()=>{const s=sample('awaiting_confirmation'),html=render(s);for(const member of s.roles){for(const text of [member.name,member.profession,member.title,member.stance,member.color])expect(html).toContain(text);}expect(html).toContain('确认阵容');expect(html).toContain('重新生成');expect(html).toContain('尚未确认');expect(html).not.toContain(s.roles[0]!.memberId);});
it('failure displays safe notice and retry, never old member cards',()=>{const html=render(sample('lineup_generation_failed'));expect(html).toContain('重试生成');expect(html).toContain('阵容生成超时');expect(html).not.toContain('member-card');});
it('confirmed is read-only with no start or regenerate',()=>{const html=render(sample('lineup_confirmed'));expect(html).toContain('阵容已确认，讨论功能将在后续阶段启用。');expect(html).not.toContain('>重新生成<');expect(html).not.toContain('>确认阵容<');expect(html).toContain('member-card');});
it('busy disables both competing actions with submit feedback',()=>{const html=render(sample('awaiting_confirmation'),true);expect(html.match(/disabled=""/g)).toHaveLength(2);expect(html).toContain('正在提交');});
it('timeout and offline notices expose manual GET recovery without faking failure',()=>{for(const text of ['状态获取超时，请重新检查','网络连接中断，正在等待恢复……']){const html=render(sample('generating_lineup'),false,text);expect(html).toContain(text);expect(html).toContain('重新检查状态');expect(html).not.toContain('重试生成');}});
it('provider text is escaped and never interpreted as HTML',()=>{const s=sample('awaiting_confirmation');s.roles[0]!.stance='<script>private()</script>';const html=render(s);expect(html).toContain('&lt;script&gt;');expect(html).not.toContain('<script>');});
