import {spawn} from 'node:child_process';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
const root='evidence/stage-7',raw=root+'/raw';mkdirSync(raw,{recursive:true});
const env={...process.env,DEEPSEEK_API_KEY:'',ROSTER_PROVIDER:'fake',DISCUSSION_PROVIDER:'fake',VITE_DISCUSSION_DEMO:'',NODE_OPTIONS:`--import=${JSON.stringify(pathToFileURL(resolve('scripts/local-network-only.mjs')).href)}`,E2E_EVIDENCE_ROOT:root,E2E_LOCAL_EVIDENCE_ROOT:root};
const commands=[['initial backend build',['node_modules/typescript/bin/tsc','-p','tsconfig.build.json']],['dependencies',['scripts/check-dependencies.mjs']],['backend',['node_modules/vitest/vitest.mjs','run','--config','vitest.config.ts','--reporter=json','--outputFile='+raw+'/backend.json']],['frontend',['node_modules/vitest/vitest.mjs','run','--config','web/vitest.config.ts','--reporter=json','--outputFile='+raw+'/frontend.json']],...['tsconfig.json','web/tsconfig.json','tsconfig.e2e.json','tsconfig.startup.json'].map(p=>['typecheck '+p,['node_modules/typescript/bin/tsc','-p',p,'--noEmit']]),['backend build',['node_modules/typescript/bin/tsc','-p','tsconfig.build.json']],['frontend build',['node_modules/vite/bin/vite.js','build','--config','web/vite.config.ts']],['startup build',['node_modules/typescript/bin/tsc','-p','tsconfig.startup.json']],['Fake E2E',['node_modules/playwright/cli.js','test','--config','playwright.stage5c.config.ts']],['HTTP adapter E2E',['node_modules/playwright/cli.js','test','--config','playwright.stage6a.config.ts']],['shared startup rehearsal',['scripts/stage6b-dry-run.mjs']]];
const report={stage:7,codeRevision:process.env.DELIVERY_REVISION??'working tree; see candidate record',directory:process.cwd(),node:process.version,startedAt:new Date().toISOString(),officialRequests:0,networkBoundary:'child fetch loopback only; Fake and injected local stub; no env file loading',commands:[]};
for(const [name,args] of commands){console.log(name);const startedAt=new Date().toISOString();let output='';const code=await new Promise((resolveCode,reject)=>{const c=spawn(process.execPath,args,{env,windowsHide:true,stdio:['ignore','pipe','pipe']});c.stdout.on('data',b=>output+=b);c.stderr.on('data',b=>output+=b);c.once('error',reject);c.once('exit',code=>resolveCode(code));});report.commands.push({name,args,startedAt,endedAt:new Date().toISOString(),exitCode:code,output});writeFileSync(root+'/verification.json',JSON.stringify(report,null,2));console.log(name+' exit '+code);if(code!==0){process.exitCode=1;break;}}
if(report.commands.length===commands.length&&report.commands.every(c=>c.exitCode===0)){const b=JSON.parse(readFileSync(raw+'/backend.json')),f=JSON.parse(readFileSync(raw+'/frontend.json'));report.counts={backend:b.numPassedTests,frontend:f.numPassedTests,backendPending:b.numPendingTests,frontendPending:f.numPendingTests,fakeE2E:JSON.parse(readFileSync(raw+'/e2e.json')).stats,httpE2E:JSON.parse(readFileSync(raw+'/local-e2e.json')).stats};}report.finishedAt=new Date().toISOString();writeFileSync(root+'/verification.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report.counts??{}));
