import {providerLabel} from './provider-label.js';
import type {DraftSnapshot} from './api.js';
import type {ConnectionState} from './discussion-stream.js';
import {useLayoutEffect,useRef,useState} from 'react';
import {statusLabels} from './api.js';
import './studio.css';
export interface StudioProps {snapshot:DraftSnapshot;connection:ConnectionState;busy:boolean;error:string;stop:()=>void;reconnect:()=>void;back:()=>void}
export function followTranscript(distance:number){return distance<=48;}
const labels:Record<ConnectionState,string>={connecting:'正在连接实时记录',live:'实时连接正常',recovering:'连接中断，正在恢复',manual:'自动恢复未成功，请手动重新连接',closed:'记录已同步，连接已关闭'};
export function Studio({snapshot:s,connection,busy,error,stop,reconnect,back}:StudioProps){
 const [tab,setTab]=useState('transcript'),[unread,setUnread]=useState(false);const transcript=useRef<HTMLDivElement>(null),follow=useRef(true);
 useLayoutEffect(()=>{const box=transcript.current;if(!box)return;if(follow.current){box.scrollTop=box.scrollHeight;setUnread(false);}else setUnread(true);},[s.utterances.length,s.summary]);
 const bottom=()=>{const box=transcript.current;if(box)box.scrollTop=box.scrollHeight;follow.current=true;setUnread(false);};
 const jump=(id:string)=>{setTab('transcript');requestAnimationFrame(()=>{const el=document.getElementById('utterance-'+id);el?.scrollIntoView({block:'center'});el?.focus({preventScroll:true});follow.current=false;});};
 const source=(id:string)=>{const u=s.utterances.find(u=>u.id===id);return u?`第${u.seq}条 · ${s.roles.find(m=>m.memberId===u.roleId)?.name??'嘉宾'}`:'发言来源';};
 const links=(ids:string[])=><div className="evidence-links">发言依据：{ids.map(id=><button key={id} onClick={()=>jump(id)}>{source(id)}</button>)}</div>;
 return <main className="studio" aria-label="讨论演播厅" data-tab={tab}>
  <header className="studio-heading"><div className="studio-topic"><span className="fake-label">{providerLabel()}</span><h2>{s.topic}</h2><div className="studio-status"><span className="badge" data-testid="discussion-status">{statusLabels[s.status]}</span><span role="status" data-testid="connection-status">{labels[connection]}</span></div></div><div className="studio-controls"><button onClick={back}>返回讨论列表</button>{s.status==='running'&&<button className="stop-button" disabled={busy} onClick={stop}>{busy?'正在请求结束…':'结束讨论'}</button>}{s.status==='stopping'&&<span role="status">正在收尾，请等待总结</span>}{['recovering','manual'].includes(connection)&&<button onClick={reconnect}>重新连接</button>}</div></header>
  {error&&<p className="error" role="alert">{error}</p>}{s.status==='failed'&&<p className="error" role="alert">{s.lastNotice?.message??'讨论已中断，已提交记录仍然保留。'}</p>}
  <nav className="studio-tabs" aria-label="演播厅区域">{[['transcript','发言记录'],['roles','嘉宾状态'],['findings','共识与分歧']].map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key!)}>{label}</button>)}</nav>
  <div className="studio-grid">
   <section className="studio-pane studio-roles" aria-label="嘉宾状态"><div className="studio-pane-title"><h3>嘉宾状态</h3><p>1 位主持人 / {s.expertCount} 位专家</p></div><div className="studio-scroll" tabIndex={0}>{s.roles.map(m=>{const state=s.roleStates?.find(r=>r.roleId===m.memberId);return <article className="role-window" key={m.memberId}><div className="member-role"><span className="member-color" style={{backgroundColor:m.color}} aria-hidden="true"/>{m.role==='moderator'?'主持人':'专家'}<span className="role-state">{state?.status==='preparing'?'准备发言':state?.status==='speaking'?'发言中':'待机'}</span></div><h4>{m.name}</h4><p>{m.profession} · {m.title}</p><p className="role-focus">{state?.publicFocus??'暂无公开关注点'}</p></article>;})}</div></section>
   <section className="studio-pane studio-transcript" aria-label="发言记录"><div className="studio-pane-title"><h3>发言记录 <span>{s.utterances.length} 条</span></h3><p>只显示已提交的公开发言</p></div><div className="studio-scroll transcript-scroll" ref={transcript} tabIndex={0} onScroll={()=>{const box=transcript.current;if(box){follow.current=followTranscript(box.scrollHeight-box.clientHeight-box.scrollTop);if(follow.current)setUnread(false);}}}>
    {!s.utterances.length&&<p className="empty">正在等待主持人开场。</p>}{s.utterances.map(u=>{const m=s.roles.find(m=>m.memberId===u.roleId);return <article className="utterance" id={'utterance-'+u.id} tabIndex={-1} key={u.id} data-testid="utterance" data-seq={u.seq}><div className="utterance-heading"><span className="member-color" style={{backgroundColor:m?.color}} aria-hidden="true"/><strong>{m?.name??'嘉宾'}</strong><span>{m?.role==='moderator'?'主持人':'专家'} · 第{u.seq}条</span></div><p className="utterance-identity">{m?.profession} · {m?.title}</p>{u.sentences.map((sentence,i)=><p key={i} className="utterance-text">{sentence}</p>)}{u.replyToUtteranceIds.length>0&&links(u.replyToUtteranceIds)}</article>;})}
    {s.summary&&<section className="discussion-summary" aria-label="结束总结"><h3>结束总结</h3>{s.summary.status==='ready'?<p>{s.summary.text}</p>:<p className="error">讨论已结束，但总结生成失败。</p>}<p className="help">依据已保存的 {s.summary.sourceTranscriptVersion} 条公开发言</p></section>}
   </div>{unread&&<button className="new-messages" onClick={bottom}>有新发言，回到底部</button>}</section>
   <section className="studio-pane studio-findings" aria-label="共识与分歧"><div className="studio-pane-title"><h3>共识与分歧</h3><p>{s.synthesis?`已覆盖至第 ${s.synthesis.sourceTranscriptVersion} 条发言`:'尚未形成可确认的观点'}</p>{s.synthesis&&s.synthesis.sourceTranscriptVersion<s.transcriptVersion&&<p>后续发言尚未纳入本次提炼</p>}</div><div className="studio-scroll" tabIndex={0}>{s.synthesisState==='preparing'&&<p className="help" role="status">正在更新观点</p>}{s.synthesisState==='failed'&&<p className="error">本次提炼未完成，保留上一份有效结果。</p>}{(['consensus','disagreement'] as const).map(kind=><section className="finding-group" key={kind}><h4>{kind==='consensus'?'已有共识':'仍有分歧'}</h4>{!s.synthesis?.items.some(f=>f.kind===kind)&&<p className="help">{kind==='consensus'?'暂未形成可确认的共识。':'暂无已提炼的分歧。'}</p>}{s.synthesis?.items.filter(f=>f.kind===kind).map(f=><article className="finding" key={f.id} data-testid="finding"><p>{f.text}</p>{f.positions.map((position,i)=><p key={i} className="finding-position">立场{i+1}：{position.text}</p>)}{links(f.evidenceUtteranceIds)}</article>)}</section>)}</div></section>
  </div>
 </main>;
}
